FROM node:22-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package*.json ./

RUN npm install && npm cache clean --force

RUN npm install -g nodemon

COPY server/ ./server/

EXPOSE 3001

CMD ["npx", "nodemon", "server/index.js"]
